### ISSUE TITLE
Lots of server errors

### ISSUE THREAD

**Issue by puiterwijk** [abrt/faf#501]
The server is seeing a lot of errors like:
[Fri Apr 22 18:43:57.528541 2016] [:error] [pid 23115] ERROR:root:u'file_name'
[Fri Apr 22 18:43:57.528585 2016] [:error] [pid 23115] Traceback (most recent call last):
[Fri Apr 22 18:43:57.528593 2016] [:error] [pid 23115]   File "/usr/lib/python2.7/site-packages/webfaf/reports.py", line 617, in new
[Fri Apr 22 18:43:57.528598 2016] [:error] [pid 23115]     opsysrelease_id=osr_id)
[Fri Apr 22 18:43:57.528602 2016] [:error] [pid 23115]   File "/usr/lib/python2.7/site-packages/pyfaf/ureport.py", line 538, in is_known
[Fri Apr 22 18:43:57.528606 2016] [:error] [pid 23115]     report_hash = problemplugin.hash_ureport(ureport["problem"])
[Fri Apr 22 18:43:57.528611 2016] [:error] [pid 23115]   File "/usr/lib/python2.7/site-packages/pyfaf/problemtypes/core.py", line 305, in hash_ureport
[Fri Apr 22 18:43:57.528615 2016] [:error] [pid 23115]     frame["file_name"].encode("ascii", "ignore")))
[Fri Apr 22 18:43:57.528619 2016] [:error] [pid 23115] KeyError: u'file_name'
[Fri Apr 22 18:43:57.547090 2016] [:error] [pid 23115] ERROR:root:u'file_name'
[Fri Apr 22 18:43:57.547118 2016] [:error] [pid 23115] Traceback (most recent call last):
[Fri Apr 22 18:43:57.547125 2016] [:error] [pid 23115]   File "/usr/lib/python2.7/site-packages/webfaf/reports.py", line 660, in new
[Fri Apr 22 18:43:57.547154 2016] [:error] [pid 23115]     report2["problem"])
[Fri Apr 22 18:43:57.547160 2016] [:error] [pid 23115]   File "/usr/lib/python2.7/site-packages/pyfaf/problemtypes/core.py", line 305, in hash_ureport
[Fri Apr 22 18:43:57.547164 2016] [:error] [pid 23115]     frame["file_name"].encode("ascii", "ignore")))
[Fri Apr 22 18:43:57.547168 2016] [:error] [pid 23115] KeyError: u'file_name'
Traceback (most recent call last):
  File "/usr/bin/retrace-server-worker", line 64, in <module>
    worker.start(kernelver=kernelver, arch=cmdline.arch)
  File "/usr/lib/python2.7/site-packages/retrace/retrace_worker.py", line 910, in start
    self._fail()
  File "/usr/lib/python2.7/site-packages/retrace/retrace_worker.py", line 148, in _fail
    raise RetraceWorkerError(errorcode=errorcode)
retrace.retrace.RetraceWorkerError: None

**Comment by marusak** [comment]
From which server are those data? Is this still happening?
Just to make it simpler to understand what is the problem:
There is technically only one problem - https://github.com/abrt/faf/blob/master/src/pyfaf/problemtypes/core.py#L305 the key `file_name` does not exist. The key is used on many places and it needs more investigating. However I will need tom ureport to reproduce it with.

Also there is some traceback from retrace-server. Unfortunately this traceback does not contain anything useful.

**Comment by xsuchy** [comment]
This happens on retrace.fedoraproject.org on daily basis.
```
Exception on /reports/new/ [POST]
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/lib/python2.7/site-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/lib/python2.7/site-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/lib/python2.7/site-packages/webfaf/reports.py", line 879, in new
    solution = find_solution(report2, db=db, osr=osr)
  File "/usr/lib/python2.7/site-packages/pyfaf/solutionfinders/__init__.py", line 117, in find_solution
    solutions = find_solutions_report(report, db, finders, osr)
  File "/usr/lib/python2.7/site-packages/pyfaf/solutionfinders/__init__.py", line 151, in find_solutions_report
    solution = solution_finder.find_solution_ureport(db, report, osr)
  File "/usr/lib/python2.7/site-packages/pyfaf/solutionfinders/probable_fix_solution_finder.py", line 52, in find_solution_ureport
    db_report = self._get_db_report(db, ureport)
  File "/usr/lib/python2.7/site-packages/pyfaf/solutionfinders/__init__.py", line 79, in _get_db_report
    report_hash = problemplugin.hash_ureport(ureport["problem"])
  File "/usr/lib/python2.7/site-packages/pyfaf/problemtypes/core.py", line 305, in hash_ureport
    frame["file_name"].encode("ascii", "ignore")))
KeyError: u'file_name'
```
