### ISSUE TITLE
Used modules not on Python3

### ISSUE THREAD

**Issue by marusak** [abrt/faf#672]
This is tracker issues for modules, those are nor present in Python3 anymore and code needs to be rewritten.

- [x] suds - In file `src/pyfaf/bugtrackers/mantisbt.py` we use suds, which is not supported anymore. There is package `python3-suds` but
```python3
>>> from suds.client import Client
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.6/site-packages/suds/client.py", line 242
    except Exception, e:
                    ^
SyntaxError: invalid syntax
```
https://src.fedoraproject.org/rpms/python3-suds states that is is **retired in Fedora**

- [x] yum - In file `src/pyfaf/rpm.py` `rpmUtils` are needed, which are provided by package `yum`.
Also in file `src/pyfaf/repos/yum.py` the module `yum` is needed.

**Comment by marusak** [comment]
This issue was fixed by #698 and #694
