### ISSUE TITLE
Comparison not supported between instances of 'OpSysRelease' and 'OpSysRelease'

### ISSUE THREAD

**Issue by mkutlak** [abrt/faf#722]
__How to reproduce:__
1) Choose at least 2 releases on Summary/Reports page. Or just Select All.
2) Press Show/Query

`Internal Server Error. This error has been logged and we will take care of it soon. Sorry.`

Weirdly there isn't such problem on Problems page.

__Error logs:__
```
Message: 'Exception on /summary/ [GET]'
Arguments: ()
--- Logging error ---
Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/lib/python3.7/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/lib/python3.7/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/lib/python3.7/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/usr/lib/python3.7/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/lib/python3.7/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/lib/python3.7/site-packages/webfaf/summary.py", line 83, in index
    index_plot_data = index_plot_data_cache(summary_form)
  File "/usr/lib/python3.7/site-packages/webfaf/summary.py", line 16, in index_plot_data_cache
    key = summary_form.caching_key()
  File "/usr/lib/python3.7/site-packages/webfaf/forms.py", line 294, in caching_key
    tuple(sorted(self.opsysreleases.data or []))))).encode("utf-8")).hexdigest()
TypeError: '<' not supported between instances of 'OpSysRelease' and 'OpSysRelease'

```

**Comment by marusak** [comment]
It seems it can be related to Python3, as it works on F27
