### ISSUE TITLE
Tests failing with SQLAlchemy 1.3+

### ISSUE THREAD

**Issue by ernestask** [abrt/faf#764]
These ones in particular, but the cause seems to be the same:

  * test_problems.py
  * test_reports.py
  * test_summary.py

```
======================================================================
ERROR: test_problem_shown (__main__.ProblemsTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib64/python3.7/site-packages/sqlalchemy/engine/base.py", line 1179, in _execute_context
    context = constructor(dialect, self, conn, *args)
  File "/usr/lib64/python3.7/site-packages/sqlalchemy/engine/default.py", line 683, in _init_compiled
    for grp, m in enumerate(parameters)
  File "/usr/lib64/python3.7/site-packages/sqlalchemy/engine/default.py", line 683, in <listcomp>
    for grp, m in enumerate(parameters)
  File "/usr/lib64/python3.7/site-packages/sqlalchemy/sql/compiler.py", line 692, in construct_params
    pd[self.bind_names[bindparam]] = bindparam.effective_value
  File "/usr/lib64/python3.7/site-packages/sqlalchemy/sql/elements.py", line 1213, in effective_value
    return self.callable()
  File "/usr/lib64/python3.7/site-packages/sqlalchemy/orm/relationships.py", line 1580, in _go
    % (column, state_str(state))
sqlalchemy.exc.InvalidRequestError: Can't resolve value for column reports.id on object <Report at 0x7f08ed553f60>; no value has been set for this column

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "./tests/test_webfaf/test_problems.py", line 36, in setUp
    self.save_report("ureport_kerneloops")
  File "/home/ekulik/Development/github.com/abrt/faf/tests/faftests/__init__.py", line 229, in save_report
    self.save_report_dict(self.load_report(filename))
  File "/home/ekulik/Development/github.com/abrt/faf/tests/faftests/__init__.py", line 211, in save_report_dict
    ureport.save(self.db, report, timestamp=mtime)
  File "/home/ekulik/Development/github.com/abrt/faf/src/pyfaf/ureport.py", line 345, in save
    timestamp=timestamp, count=count)
  File "/home/ekulik/Development/github.com/abrt/faf/src/pyfaf/ureport.py", line 235, in save_ureport2
    db_reportosrelease = get_reportosrelease(db, db_report, db_osrelease)
  File "/home/ekulik/Development/github.com/abrt/faf/src/pyfaf/queries.py", line 927, in get_reportosrelease
    .filter(st.ReportOpSysRelease.opsysrelease == osrelease)
  File "/usr/lib64/python3.7/site-packages/sqlalchemy/orm/query.py", line 3215, in first
    ret = list(self[0:1])
  File "/usr/lib64/python3.7/site-packages/sqlalchemy/orm/query.py", line 3007, in __getitem__
    return list(res)
  File "/usr/lib64/python3.7/site-packages/sqlalchemy/orm/query.py", line 3317, in __iter__
    return self._execute_and_instances(context)
  File "/usr/lib64/python3.7/site-packages/sqlalchemy/orm/query.py", line 3342, in _execute_and_instances
    result = conn.execute(querycontext.statement, self._params)
  File "/usr/lib64/python3.7/site-packages/sqlalchemy/engine/base.py", line 988, in execute
    return meth(self, multiparams, params)
  File "/usr/lib64/python3.7/site-packages/sqlalchemy/sql/elements.py", line 287, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "/usr/lib64/python3.7/site-packages/sqlalchemy/engine/base.py", line 1107, in _execute_clauseelement
    distilled_params,
  File "/usr/lib64/python3.7/site-packages/sqlalchemy/engine/base.py", line 1182, in _execute_context
    e, util.text_type(statement), parameters, None, None
  File "/usr/lib64/python3.7/site-packages/sqlalchemy/engine/base.py", line 1466, in _handle_dbapi_exception
    util.raise_from_cause(sqlalchemy_exception, exc_info)
  File "/usr/lib64/python3.7/site-packages/sqlalchemy/util/compat.py", line 383, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "/usr/lib64/python3.7/site-packages/sqlalchemy/util/compat.py", line 128, in reraise
    raise value.with_traceback(tb)
  File "/usr/lib64/python3.7/site-packages/sqlalchemy/engine/base.py", line 1179, in _execute_context
    context = constructor(dialect, self, conn, *args)
  File "/usr/lib64/python3.7/site-packages/sqlalchemy/engine/default.py", line 683, in _init_compiled
    for grp, m in enumerate(parameters)
  File "/usr/lib64/python3.7/site-packages/sqlalchemy/engine/default.py", line 683, in <listcomp>
    for grp, m in enumerate(parameters)
  File "/usr/lib64/python3.7/site-packages/sqlalchemy/sql/compiler.py", line 692, in construct_params
    pd[self.bind_names[bindparam]] = bindparam.effective_value
  File "/usr/lib64/python3.7/site-packages/sqlalchemy/sql/elements.py", line 1213, in effective_value
    return self.callable()
  File "/usr/lib64/python3.7/site-packages/sqlalchemy/orm/relationships.py", line 1580, in _go
    % (column, state_str(state))
sqlalchemy.exc.StatementError: (sqlalchemy.exc.InvalidRequestError) Can't resolve value for column reports.id on object <Report at 0x7f08ed553f60>; no value has been set for this column
[SQL: SELECT reportopsysreleases.report_id AS reportopsysreleases_report_id, reportopsysreleases.opsysrelease_id AS reportopsysreleases_opsysrelease_id, reportopsysreleases.count AS reportopsysreleases_count 
FROM reportopsysreleases 
WHERE %(param_1)s = reportopsysreleases.report_id AND %(param_2)s = reportopsysreleases.opsysrelease_id 
 LIMIT %(param_3)s]
[parameters: [{}]]
```

**Comment by ernestask** [comment]
Bisected to https://github.com/sqlalchemy/sqlalchemy/commit/d5c2db437e584af9f1224ce28e3cec3618b7d90e.

**Comment by ernestask** [comment]
The objects used in filtering don’t have their primary keys generated, so looks like we need to flush the session after each `add()` call? Furthermore, there are some ambiguous `JOIN`s, which are also a 1.3 thing: https://github.com/sqlalchemy/sqlalchemy/commit/7dcfd1e019e1c0ebceba06d6684f5bf64a2efb71.

```
======================================================================
ERROR: test_problem_shown (__main__.ProblemsTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "./tests/test_webfaf/test_problems.py", line 46, in test_problem_shown
    r = self.app.get("/problems/")
  File "/usr/lib/python3.7/site-packages/werkzeug/test.py", line 830, in get
    return self.open(*args, **kw)
  File "/usr/lib/python3.7/site-packages/flask/testing.py", line 200, in open
    follow_redirects=follow_redirects
  File "/usr/lib/python3.7/site-packages/werkzeug/test.py", line 803, in open
    response = self.run_wsgi_app(environ, buffered=buffered)
  File "/usr/lib/python3.7/site-packages/werkzeug/test.py", line 716, in run_wsgi_app
    rv = run_wsgi_app(self.application, environ, buffered=buffered)
  File "/usr/lib/python3.7/site-packages/werkzeug/test.py", line 923, in run_wsgi_app
    app_rv = app(environ, start_response)
  File "/usr/lib/python3.7/site-packages/flask/app.py", line 2309, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/lib/python3.7/site-packages/flask/app.py", line 2295, in wsgi_app
    response = self.handle_exception(e)
  File "/usr/lib/python3.7/site-packages/flask/app.py", line 1741, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/lib/python3.7/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/usr/lib/python3.7/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/lib/python3.7/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/lib/python3.7/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/lib/python3.7/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/usr/lib/python3.7/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/lib/python3.7/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/ekulik/Development/github.com/abrt/faf/src/webfaf/problems.py", line 422, in dashboard
    problems_list_table_rows_cache(filter_form, pagination)
  File "/home/ekulik/Development/github.com/abrt/faf/src/webfaf/problems.py", line 403, in problems_list_table_rows_cache
    p = get_problems(filter_form, pagination)
  File "/home/ekulik/Development/github.com/abrt/faf/src/webfaf/problems.py", line 390, in get_problems
    solution=filter_form.solution)
  File "/home/ekulik/Development/github.com/abrt/faf/src/webfaf/problems.py", line 68, in query_problems
    .join(Report)
  File "/usr/lib64/python3.7/site-packages/sqlalchemy/orm/query.py", line 2235, in join
    from_joinpoint=from_joinpoint,
  File "<string>", line 2, in _join
  File "/usr/lib64/python3.7/site-packages/sqlalchemy/orm/base.py", line 220, in generate
    fn(self, *args[1:], **kw)
  File "/usr/lib64/python3.7/site-packages/sqlalchemy/orm/query.py", line 2414, in _join
    left, right, onclause, prop, create_aliases, outerjoin, full
  File "/usr/lib64/python3.7/site-packages/sqlalchemy/orm/query.py", line 2437, in _join_left_to_right
    ) = self._join_determine_implicit_left_side(left, right, onclause)
  File "/usr/lib64/python3.7/site-packages/sqlalchemy/orm/query.py", line 2568, in _join_determine_implicit_left_side
    "Can't determine which FROM clause to join "
sqlalchemy.exc.InvalidRequestError: Can't determine which FROM clause to join from, there are multiple FROMS which can join to this entity. Try adding an explicit ON clause to help resolve the ambiguity.
```

**Comment by qris** [comment]
If you end up here searching for this error message, it's likely that you're querying a relationship for objects that have not yet been added to a session, so they have no primary key. This is newly an error in SQLAlchemy 1.3; previously it would just return no results.

For example, the following code triggers it:

```python
from sqlalchemy import Column, ForeignKey, Integer, create_engine
from sqlalchemy.ext.declarative import declarative_base
from sqlalchemy.orm import relationship, sessionmaker

Base = declarative_base()

class House(Base):
    __tablename__ = 'house'
    id = Column(Integer, primary_key=True)

class Cat(Base):
    __tablename__ = 'cat'
    id = Column(Integer, primary_key=True)
    id_house = Column(Integer, ForeignKey(House.id))
    house = relationship(House, backref="cats")
    
engine = create_engine('sqlite:///:memory:')

Base.metadata.create_all(engine)

DBSession = sessionmaker(bind=engine)
session = DBSession(autocommit=True)

session.begin()
my_house = House()
my_cat = Cat(house=my_house)
# session.add(my_house)
# session.add(my_cat)
session.query(House).filter(House.cats.contains(my_cat)).all()
```

Produces:

> sqlalchemy.exc.StatementError: (sqlalchemy.exc.InvalidRequestError) Can't resolve value for column cat.id_house on object <Cat at 0x2016659db38>; no value has been set for this column
