### ISSUE TITLE
Kerneloops retracing - line2_srcline (ValueError: invalid literal for int)

### ISSUE THREAD

**Issue by mkutlak** [abrt/faf#770]
Did parsing go wrong?
```
CRITICAL:faf:Action failed unexpectedly: ValueError: invalid literal for int() with base 10: '57:5'
Traceback (most recent call last):
  File "/usr/bin/faf", line 137, in <module>
    main()
  File "/usr/bin/faf", line 117, in main
    exitcode = cmdline.func(cmdline, db)
  File "/usr/lib/python2.7/site-packages/pyfaf/actions/retrace.py", line 158, in run
    problemplugin.retrace(db, task)
  File "/usr/lib/python2.7/site-packages/pyfaf/problemtypes/kerneloops.py", line 664, in retrace
    results = addr2line(abspath, address, debug_dir)
  File "/usr/lib/python2.7/site-packages/pyfaf/retrace.py", line 197, in addr2line
    line2_srcline = int(line2_parts[1])
ValueError: invalid literal for int() with base 10: '57:5'
```

**Comment by ernestask** [comment]
I suppose there is no oops to go with that exception?

**Comment by ernestask** [comment]
Ah, so, looking at the elfutils code, it can also spit out a column number. Since we do a single split on colon, that might be line + column above.
