### ISSUE TITLE
pull-reports: action failed

### ISSUE THREAD

**Issue by mkutlak** [abrt/faf#864]
This error happend on bugreport server. 

``` bash
CRITICAL:faf:Action failed unexpectedly: TypeError: 'type' object does not support item assignment
Traceback (most recent call last):
  File "/usr/bin/faf", line 137, in <module>
    main()
  File "/usr/bin/faf", line 117, in main
    exitcode = cmdline.func(cmdline, db)
  File "/usr/lib/python2.7/site-packages/pyfaf/actions/pull_reports.py", line 141, in run
    self._load_known()
  File "/usr/lib/python2.7/site-packages/pyfaf/actions/pull_reports.py", line 66, in _load_known
    self._full_pickle = pickle.load(f)
TypeError: 'type' object does not support item assignment
```

FAF version:
```
faf-1.3.7-1.el7.noarch
```

**Comment by mgrabovsky** [comment]
It's hard to see how this error could come up in normal operation short of data corruption. #799 might have potentially fixed this.

**Comment by xsuchy** [comment]
OK. closing for now. Lets reopen if it happens again.
