### ISSUE TITLE
Container instructions do not work

### ISSUE THREAD

**Issue by djuarezg** [abrt/faf#908]
Regarding the instructions on https://hub.docker.com/r/abrt/faf-image, all wen well except for some minor adaptations I had to use:

```bash
podman volume create volume_name
podman pod create -p 5432:5432 -p 6379:6379 -p 8080:8080 --name pod_name
podman run --pod pod_name -v /tmp/podman_tests:/var/lib/pgsql/data --privileged -e POSTGRESQL_ADMIN_PASSWORD=scrt --name db -dit abrt/postgres-semver
podman exec db sh -c "psql -c \"SELECT 1 FROM pg_roles WHERE rolname='faf'\" | grep -q 1 || yes scrt | createuser -Ps faf"
podman run --pod pod_name --privileged --name faf-redis --hostname faf-redis -dit redis
podman run --pod pod_name --privileged --name faf -dit -e PGHOST=localhost -e PGUSER=faf -e PGPASSWORD=scrt -e PGPORT=5432 -e PGDATABASE=faf \
-e RDSBROKER=redis://faf-redis:6379/0 -e RDSBACKEND=redis://faf-redis:6379/0 abrt/faf-image:2.2.0
```

The problem is that with such instructions, when checking the webUI, I get:

```
Internal Server Error. This error has been logged and we will take care of it soon. Sorry. 
```

On the server side:

```
[2020-05-07 12:27:15] INFO:faf.PullReleases: Downloading releases from remote database
[2020-05-07 12:27:20] INFO:faf.PullReleases: Adding release 'rawhide' (ACTIVE)
[2020-05-07 12:27:20] INFO:faf.PullReleases: Adding release 'ln' (ACTIVE)
[2020-05-07 12:27:20] INFO:faf.PullReleases: Adding release 'l' (ACTIVE)
[2020-05-07 12:27:20] INFO:faf.PullReleases: Adding release '30' (ACTIVE)
[2020-05-07 12:27:20] INFO:faf.PullReleases: Adding release '31' (ACTIVE)
[2020-05-07 12:27:20] INFO:faf.PullReleases: Adding release '32' (ACTIVE)
[2020-05-07 12:27:20] INFO:faf.PullReleases: Adding release '33' (ACTIVE)
[uWSGI] getting INI configuration from /etc/uwsgi.ini
setting capability setgid [6]
setting capability setuid [7]
AH00558: httpd: Could not reliably determine the server's fully qualified domain name, using fe80::94a9:b8ff:fed4:4489%eth0. Set the 'ServerName' directive globally to suppress this message
celery multi v4.3.0 (rhubarb)
> Starting nodes...
Traceback (most recent call last):
  File "/usr/lib64/python3.8/runpy.py", line 193, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib64/python3.8/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/usr/lib/python3.8/site-packages/celery/__main__.py", line 20, in <module>
    main()
  File "/usr/lib/python3.8/site-packages/celery/__main__.py", line 16, in main
    _main()
  File "/usr/lib/python3.8/site-packages/celery/bin/celery.py", line 322, in main
    cmd.execute_from_commandline(argv)
  File "/usr/lib/python3.8/site-packages/celery/bin/celery.py", line 496, in execute_from_commandline
    super(CeleryCommand, self).execute_from_commandline(argv)))
  File "/usr/lib/python3.8/site-packages/celery/bin/base.py", line 298, in execute_from_commandline
    return self.handle_argv(self.prog_name, argv[1:])
  File "/usr/lib/python3.8/site-packages/celery/bin/celery.py", line 488, in handle_argv
    return self.execute(command, argv)
  File "/usr/lib/python3.8/site-packages/celery/bin/celery.py", line 416, in execute
    return cls(
  File "/usr/lib/python3.8/site-packages/celery/bin/base.py", line 301, in run_from_argv
    return self.handle_argv(prog_name,
  File "/usr/lib/python3.8/site-packages/celery/bin/base.py", line 385, in handle_argv
    *self.parse_options(prog_name, argv, command))
  File "/usr/lib/python3.8/site-packages/celery/bin/base.py", line 421, in parse_options
    self.parser = self.create_parser(prog_name, command)
  File "/usr/lib/python3.8/site-packages/celery/bin/base.py", line 433, in create_parser
    description=self._format_description(self.description),
  File "/usr/lib/python3.8/site-packages/celery/bin/base.py", line 455, in _format_description
    text.fill_paragraphs(text.dedent(description), width))
  File "/usr/lib/python3.8/site-packages/celery/utils/text.py", line 58, in fill_paragraphs
    return sep.join(fill(p, width) for p in s.split(sep))
  File "/usr/lib/python3.8/site-packages/celery/utils/text.py", line 58, in <genexpr>
    return sep.join(fill(p, width) for p in s.split(sep))
  File "/usr/lib64/python3.8/textwrap.py", line 391, in fill
    return w.fill(text)
  File "/usr/lib64/python3.8/textwrap.py", line 363, in fill
    return "\n".join(self.wrap(text))
  File "/usr/lib64/python3.8/textwrap.py", line 354, in wrap
    return self._wrap_chunks(chunks)
  File "/usr/lib64/python3.8/textwrap.py", line 248, in _wrap_chunks
    raise ValueError("invalid width %r (must be > 0)" % self.width)
ValueError: invalid width -2 (must be > 0)
Traceback (most recent call last):
  File "/usr/lib64/python3.8/runpy.py", line 193, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib64/python3.8/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/usr/lib/python3.8/site-packages/celery/__main__.py", line 20, in <module>
    main()
  File "/usr/lib/python3.8/site-packages/celery/__main__.py", line 16, in main
    _main()
  File "/usr/lib/python3.8/site-packages/celery/bin/celery.py", line 322, in main
    cmd.execute_from_commandline(argv)
  File "/usr/lib/python3.8/site-packages/celery/bin/celery.py", line 496, in execute_from_commandline
    super(CeleryCommand, self).execute_from_commandline(argv)))
  File "/usr/lib/python3.8/site-packages/celery/bin/base.py", line 298, in execute_from_commandline
    return self.handle_argv(self.prog_name, argv[1:])
  File "/usr/lib/python3.8/site-packages/celery/bin/celery.py", line 488, in handle_argv
    return self.execute(command, argv)
  File "/usr/lib/python3.8/site-packages/celery/bin/celery.py", line 416, in execute
    return cls(
  File "/usr/lib/python3.8/site-packages/celery/bin/worker.py", line 221, in run_from_argv
    *self.parse_options(prog_name, argv, command))
  File "/usr/lib/python3.8/site-packages/celery/bin/base.py", line 421, in parse_options
    self.parser = self.create_parser(prog_name, command)
  File "/usr/lib/python3.8/site-packages/celery/bin/base.py", line 433, in create_parser
    description=self._format_description(self.description),
  File "/usr/lib/python3.8/site-packages/celery/bin/base.py", line 455, in _format_description
    text.fill_paragraphs(text.dedent(description), width))
  File "/usr/lib/python3.8/site-packages/celery/utils/text.py", line 58, in fill_paragraphs
    return sep.join(fill(p, width) for p in s.split(sep))
  File "/usr/lib/python3.8/site-packages/celery/utils/text.py", line 58, in <genexpr>
    return sep.join(fill(p, width) for p in s.split(sep))
  File "/usr/lib64/python3.8/textwrap.py", line 391, in fill
    return w.fill(text)
  File "/usr/lib64/python3.8/textwrap.py", line 363, in fill
    return "\n".join(self.wrap(text))
  File "/usr/lib64/python3.8/textwrap.py", line 354, in wrap
    return self._wrap_chunks(chunks)
  File "/usr/lib64/python3.8/textwrap.py", line 248, in _wrap_chunks
    raise ValueError("invalid width %r (must be > 0)" % self.width)
ValueError: invalid width -2 (must be > 0)
	> worker@5b90013271a0: * Child terminated with exit code 1
FAILED
```

**Comment by djuarezg** [comment]
Is there any way for Celery (through Web interface) to run actions with debug or verbose flags or is it only possible when using uwsgi?
