### ISSUE TITLE
faf attach-centos-bugs fails

### ISSUE THREAD

**Issue by djuarezg** [abrt/faf#909]
How to reproduce:

* Set up your account under `/etc/faf/plugins/centosmantisbt.conf`
* Run `faf create-problems`

This is the resulting error:

```
[2020-05-12 09:45:52] INFO:faf.AttachCentosBugs: Bug 15042 is not a valid ABRT issue.
[2020-05-12 09:45:52] INFO:faf.AttachCentosBugs: Processing Mantis issue #17140
[2020-05-12 09:45:52] DEBUG:zeep.transports: HTTP Post to https://bugs.centos.org/api/soap/mantisconnect.php:
<?xml version='1.0' encoding='utf-8'?>
<soap-env:Envelope xmlns:soap-env="http://schemas.xmlsoap.org/soap/envelope/"><soap-env:Body><ns0:mc_issue_get xmlns:ns0="http://futureware.biz/mantisconnect"><username>djuarezg</username><password>REDACTED</password><issue_id>17140</issue_id></ns0:mc_issue_get></soap-env:Body></soap-env:Envelope>
[2020-05-12 09:45:52] DEBUG:urllib3.connectionpool: Resetting dropped connection: bugs.centos.org
[2020-05-12 09:45:53] DEBUG:urllib3.connectionpool: https://bugs.centos.org:443 "POST /api/soap/mantisconnect.php HTTP/1.1" 200 5318
[2020-05-12 09:45:53] DEBUG:zeep.transports: HTTP Response from https://bugs.centos.org/api/soap/mantisconnect.php (status: 200):
<?xml version="1.0" encoding="UTF-8"?>
<SOAP-ENV:Envelope xmlns:SOAP-ENV="http://schemas.xmlsoap.org/soap/envelope/" xmlns:ns1="http://futureware.biz/mantisconnect" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:SOAP-ENC="http://schemas.xmlsoap.org/soap/encoding/" SOAP-ENV:encodingStyle="http://schemas.xmlsoap.org/soap/encoding/"><SOAP-ENV:Body><ns1:mc_issue_getResponse><return xsi:type="ns1:IssueData"><id xsi:type="xsd:integer">17140</id><view_state xsi:type="ns1:ObjectRef"><id xsi:type="xsd:integer">10</id><name xsi:type="xsd:string">public</name></view_state><last_updated xsi:type="xsd:dateTime">2020-03-12T09:20:42+00:00</last_updated><project xsi:type="ns1:ObjectRef"><id xsi:type="xsd:integer">32</id><name xsi:type="xsd:string">CentOS-8</name></project><category xsi:type="xsd:string">plymouth</category><priority xsi:type="ns1:ObjectRef"><id xsi:type="xsd:integer">30</id><name xsi:type="xsd:string">normal</name></priority><severity xsi:type="ns1:ObjectRef"><id xsi:type="xsd:integer">60</id><name xsi:type="xsd:string">major</name></severity><status xsi:type="ns1:ObjectRef"><id xsi:type="xsd:integer">10</id><name xsi:type="xsd:string">new</name></status><reporter xsi:type="ns1:AccountData"><id xsi:type="xsd:integer">5417</id><name xsi:type="xsd:string">olahaye74</name></reporter><summary xsi:type="xsd:string">Plymouth crash in initrd</summary><version xsi:type="xsd:string">8.1.1911</version><reproducibility xsi:type="ns1:ObjectRef"><id xsi:type="xsd:integer">10</id><name xsi:type="xsd:string">always</name></reproducibility><date_submitted xsi:type="xsd:dateTime">2020-03-12T09:20:42+00:00</date_submitted><sponsorship_total xsi:type="xsd:integer">0</sponsorship_total><resolution xsi:type="ns1:ObjectRef"><id xsi:type="xsd:integer">10</id><name xsi:type="xsd:string">open</name></resolution><description xsi:type="xsd:string">Bug similar to https://bugs.centos.org/view.php?id=9644 but for CentOS-8.1&#13;
&#13;
Hitting this issue on CentOS-8.1(CentOS Linux release 8.1.1911 (Core) )&#13;
plymouth-0.9.3-15.el8.x86_64&#13;
&#13;
Crash:&#13;
access("/run/udev/control", F_OK)       = 0&#13;
socket(AF_NETLINK, SOCK_RAW|SOCK_CLOEXEC|SOCK_NONBLOCK, NETLINK_KOBJECT_UEVENT) = 7&#13;
setsockopt(7, SOL_SOCKET, SO_ATTACH_FILTER, {len=18, filter=0x7fffa210cc00}, 16) = 0&#13;
bind(7, {sa_family=AF_NETLINK, nl_pid=0, nl_groups=0x000002}, 12) = 0&#13;
getsockname(7, {sa_family=AF_NETLINK, nl_pid=4681, nl_groups=0x000002}, [12]) = 0&#13;
setsockopt(7, SOL_SOCKET, SO_PASSCRED, [1], 4) = 0&#13;
epoll_ctl(3, EPOLL_CTL_ADD, 7, {EPOLLERR|EPOLLHUP, {u32=952875488, u64=94412923976160}}) = 0&#13;
epoll_ctl(3, EPOLL_CTL_MOD, 7, {EPOLLIN|EPOLLERR|EPOLLHUP, {u32=952875488, u64=94412923976160}}) = 0&#13;
getpid()                                = 4681&#13;
gettid()                                = 4681&#13;
getrandom("\xfa\xd7\x9b\xf5\x0d\xec\xb1\x40\xd5\x66\xbc\x19\xdf\xa2\xf0\x55", 16, GRND_NONBLOCK) = 16&#13;
access("/sys/sub         = -1 ENOENT (No such file or directory)&#13;
openat(AT_FDCWD, "/sys/bus", O_RDONLY|O_NONBLOCK|O_CLOEXEC|O_DIRECTORY) = 9&#13;
fstat(9, {st_mode=S_IFDIR|0755, st_size=0, ...}) = 0&#13;
getdents64(9, /* 34 entries */, 32768)  = 952&#13;
getdents64(9, /* 0 entries */, 32768)   = 0&#13;
close(9)                                = 0&#13;
openat(AT_FDCWD, "/sys/class", O_RDONLY|O_NONBLOCK|O_CLOEXEC|O_DIRECTORY) = 9&#13;
fstat(9, {st_mode=S_IFDIR|0755, st_size=0, ...}) = 0&#13;
getdents64(9, /* 50 entries */, 32768)  = 1448&#13;
getdents64(9, /* 0 entries */, 32768)   = 0&#13;
close(9)                                = 0&#13;
write(2, "plymouthd: ply-event-loop.c:913: ply_event_loop_watch_for_timeout: Assertion `seconds &gt; 0.0' failed.\n", 101) = 101&#13;
mmap(NULL, 4096, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7f6dcee12000&#13;
rt_sigprocmask(SIG_UNBLOCK, [ABRT], NULL, 8) = 0&#13;
rt_sigprocmask(SIG_BLOCK, ~[RTMIN RT_1], [], 8) = 0&#13;
getpid()                                = 4681&#13;
gettid()                                = 4681&#13;
tgkill(4681, 4681, SIGABRT)             = 0&#13;
rt_sigprocmask(SIG_SETMASK, [], NULL, 8) = 0&#13;
--- SIGABRT {si_signo=SIGABRT, si_code=SI_TKILL, si_pid=4681, si_uid=0} ---&#13;
openat(AT_FDCWD, "/dev/tty1", O_RDWR|O_NOCTTY) = 9&#13;
ioctl(9, KDSETMODE, 0)                  = 0&#13;
write(9, "\33[?25h\0", 7)               = 7&#13;
ioctl(9, TCGETS, {B38400 opost isig icanon echo ...}) = 0&#13;
ioctl(9, SNDCTL_TMR_CONTINUE or TCSETSF, {B38400 opost isig icanon echo ...}) = 0&#13;
close(9)                                = 0&#13;
unlink("/var/run/plymouth/pid")         = 0&#13;
</description><steps_to_reproduce xsi:type="xsd:string">Use those kernels and ignited.img. run them using Qemu. Plymouth will crash&#13;
when you reach the shell, you'll have many commands to debug including strace.&#13;
http://olivier.lahaye1.free.fr/SystemImager/plymouth_crash/&#13;
</steps_to_reproduce><attachments SOAP-ENC:arrayType="ns1:AttachmentData[0]" xsi:type="SOAP-ENC:Array"/><monitors SOAP-ENC:arrayType="ns1:AccountData[0]" xsi:type="SOAP-ENC:Array"/><sticky xsi:type="xsd:boolean">false</sticky><tags SOAP-ENC:arrayType="ns1:ObjectRef[0]" xsi:type="SOAP-ENC:Array"/></return></ns1:mc_issue_getResponse></SOAP-ENV:Body></SOAP-ENV:Envelope>

[2020-05-12 09:45:53] CRITICAL:faf: Action failed unexpectedly: TypeError: 'NoneType' object is not iterable
```

Not sure if also related but when trying to manually link a report with [an existing bug](https://bugs.centos.org/view.php?id=17356):

```
Failed to fetch bug. 'CentosMantis' object has no attribute 'download_bug_to_storage_no_retry'
```

**Comment by ernestask** [comment]
https://github.com/abrt/faf/blob/9c0c751404c7677b383e8fc9cc80fcd664a390a2/src/webfaf/reports.py#L666

Seems that the code has been broken since the beginning.

**Comment by ernestask** [comment]
Can you re-run the action with `faf --debug`, so it spits out a stack trace?

**Comment by djuarezg** [comment]
```
$ faf attach-centos-bugs --debug --verbose
(...)
[2020-05-13 12:34:43] INFO:faf.AttachCentosBugs: Bug 15042 is not a valid ABRT issue.
[2020-05-13 12:34:43] INFO:faf.AttachCentosBugs: Processing Mantis issue #17140
[2020-05-13 12:34:43] DEBUG:zeep.transports: HTTP Post to https://bugs.centos.org/api/soap/mantisconnect.php:
<?xml version='1.0' encoding='utf-8'?>
<soap-env:Envelope xmlns:soap-env="http://schemas.xmlsoap.org/soap/envelope/"><soap-env:Body><ns0:mc_issue_get xmlns:ns0="http://futureware.biz/mantisconnect"><username>djuarezg</username><password><REDACTED></password><issue_id>17140</issue_id></ns0:mc_issue_get></soap-env:Body></soap-env:Envelope>
[2020-05-13 12:34:43] DEBUG:urllib3.connectionpool: Resetting dropped connection: bugs.centos.org
[2020-05-13 12:34:44] DEBUG:urllib3.connectionpool: https://bugs.centos.org:443 "POST /api/soap/mantisconnect.php HTTP/1.1" 200 5318
[2020-05-13 12:34:44] DEBUG:zeep.transports: HTTP Response from https://bugs.centos.org/api/soap/mantisconnect.php (status: 200):
<?xml version="1.0" encoding="UTF-8"?>
<SOAP-ENV:Envelope xmlns:SOAP-ENV="http://schemas.xmlsoap.org/soap/envelope/" xmlns:ns1="http://futureware.biz/mantisconnect" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:SOAP-ENC="http://schemas.xmlsoap.org/soap/encoding/" SOAP-ENV:encodingStyle="http://schemas.xmlsoap.org/soap/encoding/"><SOAP-ENV:Body><ns1:mc_issue_getResponse><return xsi:type="ns1:IssueData"><id xsi:type="xsd:integer">17140</id><view_state xsi:type="ns1:ObjectRef"><id xsi:type="xsd:integer">10</id><name xsi:type="xsd:string">public</name></view_state><last_updated xsi:type="xsd:dateTime">2020-03-12T09:20:42+00:00</last_updated><project xsi:type="ns1:ObjectRef"><id xsi:type="xsd:integer">32</id><name xsi:type="xsd:string">CentOS-8</name></project><category xsi:type="xsd:string">plymouth</category><priority xsi:type="ns1:ObjectRef"><id xsi:type="xsd:integer">30</id><name xsi:type="xsd:string">normal</name></priority><severity xsi:type="ns1:ObjectRef"><id xsi:type="xsd:integer">60</id><name xsi:type="xsd:string">major</name></severity><status xsi:type="ns1:ObjectRef"><id xsi:type="xsd:integer">10</id><name xsi:type="xsd:string">new</name></status><reporter xsi:type="ns1:AccountData"><id xsi:type="xsd:integer">5417</id><name xsi:type="xsd:string">olahaye74</name></reporter><summary xsi:type="xsd:string">Plymouth crash in initrd</summary><version xsi:type="xsd:string">8.1.1911</version><reproducibility xsi:type="ns1:ObjectRef"><id xsi:type="xsd:integer">10</id><name xsi:type="xsd:string">always</name></reproducibility><date_submitted xsi:type="xsd:dateTime">2020-03-12T09:20:42+00:00</date_submitted><sponsorship_total xsi:type="xsd:integer">0</sponsorship_total><resolution xsi:type="ns1:ObjectRef"><id xsi:type="xsd:integer">10</id><name xsi:type="xsd:string">open</name></resolution><description xsi:type="xsd:string">Bug similar to https://bugs.centos.org/view.php?id=9644 but for CentOS-8.1&#13;
&#13;
Hitting this issue on CentOS-8.1(CentOS Linux release 8.1.1911 (Core) )&#13;
plymouth-0.9.3-15.el8.x86_64&#13;
&#13;
Crash:&#13;
access("/run/udev/control", F_OK)       = 0&#13;
socket(AF_NETLINK, SOCK_RAW|SOCK_CLOEXEC|SOCK_NONBLOCK, NETLINK_KOBJECT_UEVENT) = 7&#13;
setsockopt(7, SOL_SOCKET, SO_ATTACH_FILTER, {len=18, filter=0x7fffa210cc00}, 16) = 0&#13;
bind(7, {sa_family=AF_NETLINK, nl_pid=0, nl_groups=0x000002}, 12) = 0&#13;
getsockname(7, {sa_family=AF_NETLINK, nl_pid=4681, nl_groups=0x000002}, [12]) = 0&#13;
setsockopt(7, SOL_SOCKET, SO_PASSCRED, [1], 4) = 0&#13;
epoll_ctl(3, EPOLL_CTL_ADD, 7, {EPOLLERR|EPOLLHUP, {u32=952875488, u64=94412923976160}}) = 0&#13;
epoll_ctl(3, EPOLL_CTL_MOD, 7, {EPOLLIN|EPOLLERR|EPOLLHUP, {u32=952875488, u64=94412923976160}}) = 0&#13;
getpid()                                = 4681&#13;
gettid()                                = 4681&#13;
getrandom("\xfa\xd7\x9b\xf5\x0d\xec\xb1\x40\xd5\x66\xbc\x19\xdf\xa2\xf0\x55", 16, GRND_NONBLOCK) = 16&#13;
access("/sys/sub         = -1 ENOENT (No such file or directory)&#13;
openat(AT_FDCWD, "/sys/bus", O_RDONLY|O_NONBLOCK|O_CLOEXEC|O_DIRECTORY) = 9&#13;
fstat(9, {st_mode=S_IFDIR|0755, st_size=0, ...}) = 0&#13;
getdents64(9, /* 34 entries */, 32768)  = 952&#13;
getdents64(9, /* 0 entries */, 32768)   = 0&#13;
close(9)                                = 0&#13;
openat(AT_FDCWD, "/sys/class", O_RDONLY|O_NONBLOCK|O_CLOEXEC|O_DIRECTORY) = 9&#13;
fstat(9, {st_mode=S_IFDIR|0755, st_size=0, ...}) = 0&#13;
getdents64(9, /* 50 entries */, 32768)  = 1448&#13;
getdents64(9, /* 0 entries */, 32768)   = 0&#13;
close(9)                                = 0&#13;
write(2, "plymouthd: ply-event-loop.c:913: ply_event_loop_watch_for_timeout: Assertion `seconds &gt; 0.0' failed.\n", 101) = 101&#13;
mmap(NULL, 4096, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7f6dcee12000&#13;
rt_sigprocmask(SIG_UNBLOCK, [ABRT], NULL, 8) = 0&#13;
rt_sigprocmask(SIG_BLOCK, ~[RTMIN RT_1], [], 8) = 0&#13;
getpid()                                = 4681&#13;
gettid()                                = 4681&#13;
tgkill(4681, 4681, SIGABRT)             = 0&#13;
rt_sigprocmask(SIG_SETMASK, [], NULL, 8) = 0&#13;
--- SIGABRT {si_signo=SIGABRT, si_code=SI_TKILL, si_pid=4681, si_uid=0} ---&#13;
openat(AT_FDCWD, "/dev/tty1", O_RDWR|O_NOCTTY) = 9&#13;
ioctl(9, KDSETMODE, 0)                  = 0&#13;
write(9, "\33[?25h\0", 7)               = 7&#13;
ioctl(9, TCGETS, {B38400 opost isig icanon echo ...}) = 0&#13;
ioctl(9, SNDCTL_TMR_CONTINUE or TCSETSF, {B38400 opost isig icanon echo ...}) = 0&#13;
close(9)                                = 0&#13;
unlink("/var/run/plymouth/pid")         = 0&#13;
</description><steps_to_reproduce xsi:type="xsd:string">Use those kernels and ignited.img. run them using Qemu. Plymouth will crash&#13;
when you reach the shell, you'll have many commands to debug including strace.&#13;
http://olivier.lahaye1.free.fr/SystemImager/plymouth_crash/&#13;
</steps_to_reproduce><attachments SOAP-ENC:arrayType="ns1:AttachmentData[0]" xsi:type="SOAP-ENC:Array"/><monitors SOAP-ENC:arrayType="ns1:AccountData[0]" xsi:type="SOAP-ENC:Array"/><sticky xsi:type="xsd:boolean">false</sticky><tags SOAP-ENC:arrayType="ns1:ObjectRef[0]" xsi:type="SOAP-ENC:Array"/></return></ns1:mc_issue_getResponse></SOAP-ENV:Body></SOAP-ENV:Envelope>

[2020-05-13 12:34:44] CRITICAL:faf: Action failed unexpectedly: TypeError: 'NoneType' object is not iterable
Traceback (most recent call last):
  File "/usr/bin/faf", line 152, in <module>
    main()
  File "/usr/bin/faf", line 132, in main
    exitcode = cmdline.func(cmdline, db)
  File "/usr/lib/python3.8/site-packages/pyfaf/actions/attach_centos_bugs.py", line 41, in run
    bug_dict = mbt.preprocess_bug(bug)
  File "/usr/lib/python3.8/site-packages/pyfaf/bugtrackers/mantisbt.py", line 137, in preprocess_bug
    "url": next((f.value for f in bug.custom_fields if f.field.name == "URL"), "")
TypeError: 'NoneType' object is not iterable
```

**Comment by ernestask** [comment]
These should help you:

https://github.com/abrt/faf/pull/912
https://github.com/abrt/faf/pull/914
