### ISSUE TITLE
Cannot seem to make faf retrace work

### ISSUE THREAD

**Issue by djuarezg** [abrt/faf#910]
How to reproduce:

* Configure `/etc/libreport/plugins/ureport.conf` to point to your private FAF server.
* Enable autoreporting on a CentOS 7 node `abrt-auto-reporting enabled`
* Add a CentOS repo + debuginfo repo:

```
faf repoimport dnf CentOS-Base.repo
bash-5.0$ cat CentOS-Base.repo
[base]
name=CentOS-$releasever - Base
baseurl=http://linuxsoft.cern.ch/cern/centos/$releasever/os/$basearch/
gpgcheck=0
enabled=1
priority=5

#released updates
[updates]
name=CentOS-$releasever - Updates
baseurl=http://linuxsoft.cern.ch/cern/centos/$releasever/updates/$basearch/
gpgcheck=0
enabled=1
priority=5

faf repoadd debuginfo dnf http://linuxsoft.cern.ch/centos-debuginfo/7/x86_64/
faf repoassign debuginfo "CentOS 7" x86_64
```

* Assign these repos to CentOS
* Reposync required packages: `faf reposync --name-prefix coreutils` & `faf reposync --name-prefix glibc`
* Force a crash on your node:
```
[djuarezg@localhost ~]$ sleep 10m &
[1] 344
[djuarezg@localhost ~]$ kill -SIGSEGV 344
```
* `faf save-reports` -> https://abrtanalytics.web.cern.ch/faf/reports/1/
* `faf retrace -v`:
```
[2020-05-12 12:26:36] INFO:faf.Retrace: Processing 'Crash of user-space binary' problem type
[2020-05-12 12:26:36] DEBUG:faf.Retrace: [1 / 112] Processing '__nanosleep' @ '/lib64/libc.so.6'
--- Logging error ---
Traceback (most recent call last):
  File "/usr/lib64/python3.8/logging/__init__.py", line 1081, in emit
    msg = self.format(record)
  File "/usr/lib64/python3.8/logging/__init__.py", line 925, in format
    return fmt.format(record)
  File "/usr/lib64/python3.8/logging/__init__.py", line 664, in format
    record.message = record.getMessage()
  File "/usr/lib64/python3.8/logging/__init__.py", line 369, in getMessage
    msg = msg % self.args
TypeError: %d format: a number is required, not str
Call stack:
  File "/usr/bin/faf", line 152, in <module>
    main()
  File "/usr/bin/faf", line 132, in main
    exitcode = cmdline.func(cmdline, db)
  File "/usr/lib/python3.8/site-packages/pyfaf/actions/retrace.py", line 100, in run
    pkgmap = self._get_pkgmap(db, problemplugin, db_ssources)
  File "/usr/lib/python3.8/site-packages/pyfaf/actions/retrace.py", line 51, in _get_pkgmap
    pkgs = problemplugin.find_packages_for_ssource(db, db_ssource)
  File "/usr/lib/python3.8/site-packages/pyfaf/problemtypes/core.py", line 471, in find_packages_for_ssource
    self.log_debug("Build-id: %d", db_ssource.build_id)
Message: 'Build-id: %d'
Arguments: ('398944d32cf16a67af51067a326e6c0cc14f90ed',)
[2020-05-12 12:26:36] DEBUG:faf.CoredumpProblem: File name: /usr/lib/debug/.build-id/39/8944d32cf16a67af51067a326e6c0cc14f90ed.debug
[2020-05-12 12:26:36] DEBUG:faf.CoredumpProblem: Debug Package: Not found
[2020-05-12 12:26:36] DEBUG:faf.CoredumpProblem: Binary Package: Not found
[2020-05-12 12:26:36] DEBUG:faf.CoredumpProblem: Source Package: Not found
```

Cannot retrace locally on the FAF server although packages where downloaded on the `reposync` step.

**Comment by ernestask** [comment]
Looks like a very embarrassing bug.
