### ISSUE TITLE
Installing Manually

### ISSUE THREAD

**Issue by buip** [abrt/faf#933]
Hi,

I'm following the manual installation process and I got this error. I have set up the db correctly. I'm using RHEL and I have tried installing python-dnf

```
[.....]# sudo -u faf faf-migrate-db --create-all
[2020-07-14 21:09:11] ERROR:faf: Unable to import plugin pyfaf.repos.dnf: No module named 'dnf'
[2020-07-14 21:09:11] ERROR:faf: Unable to import plugin pyfaf.problemtypes.python: invalid syntax (scheduler.py, line 58)
[2020-07-14 21:09:11] ERROR:faf: Unable to import plugin pyfaf.problemtypes.core: invalid syntax (scheduler.py, line 58)
[2020-07-14 21:09:11] ERROR:faf: Unable to import plugin pyfaf.problemtypes.java: invalid syntax (scheduler.py, line 58)
[2020-07-14 21:09:11] ERROR:faf: Unable to import plugin pyfaf.problemtypes.ruby: invalid syntax (scheduler.py, line 58)
[2020-07-14 21:09:11] ERROR:faf: Unable to import plugin pyfaf.problemtypes.kerneloops: invalid syntax (scheduler.py, line 58)
[2020-07-14 21:09:11] ERROR:faf: Unable to import plugin pyfaf.actions.save_reports: invalid syntax (scheduler.py, line 58)
[2020-07-14 21:09:12] ERROR:faf: Unable to import plugin pyfaf.actions.fedmsg_notify: No module named 'faf_schema'
[2020-07-14 21:09:12] ERROR:faf: Unable to import plugin pyfaf.actions.find_report_solution: invalid syntax (scheduler.py, line 58)
[2020-07-14 21:09:12] ERROR:faf: Unable to import plugin pyfaf.actions.create_problems: invalid syntax (scheduler.py, line 58)
Traceback (most recent call last):
  File "/usr/local/bin/faf-migrate-db", line 28, in <module>
    from pyfaf.common import get_connect_string
  File "/usr/local/lib/python3.6/site-packages/pyfaf/__init__.py", line 25, in <module>
    from . import cmdline
  File "/usr/local/lib/python3.6/site-packages/pyfaf/cmdline.py", line 25, in <module>
    from pyfaf.solutionfinders import solution_finders
  File "/usr/local/lib/python3.6/site-packages/pyfaf/solutionfinders/__init__.py", line 23, in <module>
    from pyfaf.ureport import ureport2, validate
  File "/usr/local/lib/python3.6/site-packages/pyfaf/ureport.py", line 67, in <module>
    from pyfaf.ureport_compat import ureport1to2
  File "/usr/local/lib/python3.6/site-packages/pyfaf/ureport_compat.py", line 6, in <module>
    import satyr
  File "/usr/local/lib/python3.6/site-packages/satyr/__init__.py", line 5, in <module>
    from .scheduler import QueueScheduler
  File "/usr/local/lib/python3.6/site-packages/satyr/scheduler.py", line 58
    raise exc_type, exc_value, traceback
                  ^
```

**Comment by xsuchy** [comment]
Upstream code use python3. So you must install python3-dnf package. Or you can use packages from https://copr.fedorainfracloud.org/coprs/g/abrt/faf-el8/

**Comment by buip** [comment]
Hi @xsuchy, thanks for the comment. I'm currently using RHEL 7 so I installed this instead https://copr.fedorainfracloud.org/coprs/g/abrt/faf-el7/.

After installing and setup the DB, I tried to initialize the database with `sudo -u faf faf-migrate-db --create-all`. However, I ran to the error showed above. It seems like python3-dnf is only supported on version 8

Given that, does it mean I cannot use faf on RHEL 7?

**Comment by ernestask** [comment]
The error seems to be coming from satyr, so I’ll move it there.
